name: Build & Deploy
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Build Package
        run: |
          mkdir package
          pip install -r requirements.lock --target ./package
          cd package && zip -r ../lunch_calendar.zip .
          cd .. && zip lunch_calendar.zip main.py
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: lunch_calendar
      #     path: lunch_calendar.zip
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: deploy
      - name: terraform apply
        if: github.ref == 'refs/heads/main'
        uses: dflook/terraform-apply@v1
        with:
          path: deploy
